# -*- coding: utf-8 -*-
"""Validação

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iYrRuoFamvaiGsj0tln4XmOL7qWCMUiv
"""

cpf = "01683794575"

primeiro = 0
segundo = 0
soma_nove = (int(cpf[0])*10) + (int(cpf[1])*9) + (int(cpf[2])*8) + (int(cpf[3])*7) + (int(cpf[4])*6) + (int(cpf[5])*5) + (int(cpf[6])*4) + (int(cpf[7])*3) + (int(cpf[8])*2)

resto_soma_nove = soma_nove % 11

if resto_soma_nove < 2:
    primeiro = 0
elif resto_soma_nove >= 2:
    primeiro = 11 - resto_soma_nove

soma_nove = (int(cpf[0])*11) + (int(cpf[1])*10) + (int(cpf[2])*9) + (int(cpf[3])*8) + (int(cpf[4])*7) + (int(cpf[5])*6) + (int(cpf[6])*5) + (int(cpf[7])*4) + (int(cpf[8])*3)+(int(primeiro*2))
resto_soma_nove = soma_nove % 11

if resto_soma_nove < 2:
    segundo = 0
elif resto_soma_nove >= 2:
    segundo = 11 - resto_soma_nove

if primeiro == int(cpf[9]) and segundo == int(cpf[10]):
    print("CPF válido")
else:
    print("CPF inválido")
print(cpf)